FROM node:20.14.0-alpine3.20

WORKDIR /usr/src/app

RUN npm install -g nodemon && \
    npm install express --save && \
    npm install -g express-generator && \
    npm install mysql2

# Exponemos el puerto que usará la aplicación
EXPOSE 3000

CMD ["nodemon"]
